version: '3.6'

x-shared: &shared
  restart: on-failure
  stop_signal: SIGKILL

services:
  # Locally mocked aws services
  aws:
    image: localstack/localstack
    ports:
      - 4572:4572
      - 8888:8080
    environment:
      SERVICES: s3
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - ./etc/localstack/init.d:/docker-entrypoint-initaws.d
      - ./etc/localstack/tmp:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  # Sawtooth CLI
  shell:
    <<: *shared
    image: hyperledger/sawtooth-shell:1.1
    depends_on:
      - rest-api-1
    volumes:
      - ./etc/sawtooth/cli.toml:/etc/sawtooth/cli.toml
    command: >-
      bash -c '
        sawtooth keygen &&
        tail -f /dev/null
      '

  # Transaction validator
  validator-1:
    <<: *shared
    image: hyperledger/sawtooth-validator:1.0
    security_opt:
      - apparmor:unconfined
    command: >-
      bash -c '
        sawadm keygen --force &&
        sawset genesis \
          --key /etc/sawtooth/keys/validator.priv &&
        sawadm genesis config-genesis.batch &&
        sawtooth-validator -v \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --peering dynamic \
          --scheduler serial \
          --network-auth trust
      '

  # Consensus engine
  engine-1:
    <<: *shared
    image: hyperledger/sawtooth-devmode-engine-rust:1.1
    depends_on:
      - validator-1
    command: devmode-engine-rust
      --connect tcp://validator-1:5050

  # Sawtooth REST API that communicates with the validator
  rest-api-1:
    <<: *shared
    image: hyperledger/sawtooth-rest-api:1.1
    depends_on:
      - validator-1
    ports:
      - 8008:8008
    command: sawtooth-rest-api
      --connect tcp://validator-1:4004
      --bind rest-api-1:8008

  # The web "middleware" service
  middleware-1:
    <<: *shared
    ports:
      - 8080:8080
    depends_on:
      - rest-api-1
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID?AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY?AWS_SECRET_ACCESS_KEY}
    command: npm start -- http://rest-api-1:8008

  # Claim transaction processor
  tp-claim-1:
    <<: *shared
    depends_on:
      - validator-1
    command: npm run tp-claim:start -- tcp://validator-1:4004

  # Settings Transaction Processor
  tp-settings-1:
    <<: *shared
    image: hyperledger/sawtooth-settings-tp:1.1
    depends_on:
      - validator-1
    command: settings-tp -v
      --connect tcp://validator-1:4004

  # Frontend apps
  web-insurance:
    <<: *shared
    depends_on:
      - middleware-1

  web-viewer:
    <<: *shared
    depends_on:
      - middleware-1
