version: '3.6'

x-shared:
  &shared
  restart: on-failure
  stop_signal: SIGKILL

services:
  # Transaction validator
  validator:
    <<: *shared
    image: hyperledger/sawtooth-validator:1.0
    security_opt:
      - apparmor:unconfined
    ports:
      - 4004:4004
    entrypoint: >-
      bash -c '
      sawadm keygen &&
      sawtooth keygen id_ecdsa &&
      sawset genesis --key /root/.sawtooth/keys/id_ecdsa.priv &&
      sawadm genesis config-genesis.batch &&
      sawtooth-validator -vv
      --endpoint tcp://validator:8800
      --bind component:tcp://eth0:4004
      --bind network:tcp://eth0:8800
      --bind consensus:tcp://eth0:5050
      '

  # Consensus engine
  engine:
    <<: *shared
    depends_on:
      - validator

  # Sawtooth REST API that communicates with the validator
  rest-api:
    <<: *shared
    image: hyperledger/sawtooth-rest-api:1.1
    depends_on:
      - validator
    ports:
      - 8008:8008
    entrypoint: >-
      sawtooth-rest-api
      --connect tcp://validator:4004
      --bind rest-api:8008

  # Sawtooth CLI
  shell:
    <<: *shared
    image: hyperledger/sawtooth-shell:1.1
    depends_on:
      - rest-api
    volumes:
      - ./etc/sawtooth/cli.toml:/etc/sawtooth/cli.toml
    entrypoint: >-
      bash -c '
      sawtooth keygen &&
      tail -f /dev/null
      '

  # The web "middleware" service
  middleware:
    <<: *shared
    ports:
      - 8080:8080
    depends_on:
      - rest-api
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: npm start

  # Static web server for frontend app
  web:
    <<: *shared
    depends_on:
      - middleware

  # Claim transaction processor
  tp-claim:
    <<: *shared
    depends_on:
      - validator
    command: npm run tp-claim:start -- tcp://validator:4004

  # Settings Transaction Processor
  tp-settings:
    <<: *shared
    image: hyperledger/sawtooth-settings-tp:1.1
    depends_on:
      - validator
    entrypoint: >-
      settings-tp
      -vv
      --connect tcp://validator:4004
