version: '3.7'

services:
  # Main validator
  validator:
    image: hyperledger/sawtooth-validator:1.1
    ports:
      - 4004:4004
    # start the validator with an empty genesis batch
    entrypoint: >-
      bash -c "
      sawadm keygen &&
      sawtooth keygen id_ecdsa &&
      sawset genesis --key /root/.sawtooth/keys/id_ecdsa.priv &&
      sawadm genesis config-genesis.batch &&
      sawtooth-validator -vv
      --endpoint tcp://validator:8800
      --bind component:tcp://eth0:4004
      --bind network:tcp://eth0:8800
      --bind consensus:tcp://eth0:5050
      "

  # Sawtooth REST API that communicates with the validator
  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    ports:
      - 8008:8008
    depends_on:
      - validator
    entrypoint: >-
      sawtooth-rest-api
      --connect tcp://validator:4004
      --bind rest-api:8008

  # Hyperledger Sawtooth CLI
  shell:
    image: hyperledger/sawtooth-shell:1.1
    depends_on:
      - rest-api
    volumes:
      - ./cli.toml:/etc/sawtooth/cli.toml
    entrypoint: >-
      bash -c "
      sawtooth keygen &&
      tail -f /dev/null
      "

  # The web "middleware" service
  middleware:
    ports:
      - 8080:80
    depends_on:
      - rest-api
    command: npm start
    environment:
      PORT: 80

  # Static web server for frontend app
  web:
    depends_on:
      - middleware

  # Our custom vehicle transaction processor
  tp-vehicle:
    image: fordtotalloss/sawtooth-vehicle-tp
    build: ./processor
    depends_on:
      - validator
    command: npm start -- tcp://validator:4004

  # Settings Transaction Processor
  tp-settings:
    image: hyperledger/sawtooth-settings-tp:1.1
    depends_on:
      - validator
    entrypoint: >-
      settings-tp
      -vv
      --connect tcp://validator:4004

volumes:
  middleware-db:
